###
GET http://localhost:9090/test/get



###
POST http://localhost:9090/test1/post
Content-Type: application/json

{
  "userId": "rpy",
  "username": "rpy"
}

###
POST http://localhost:9090/test/upload


###
POST http://localhost:9090/random/post
Content-Type: application/json

{
  "userId": "rpy",
  "username": "rpy"
}


###
POST http://localhost:9090/weight/post
Content-Type: application/json

{
  "userId": "rpy",
  "username": "rpy"
}



###
POST http://localhost:9090/iphash/post
Content-Type: application/json

{
  "userId": "rpy",
  "username": "rpy"
}



###
POST http://localhost:9090/robin/post
Content-Type: application/json

{
  "userId": "rpy",
  "username": "rpy"
}

